name: Upload to PyPI

on:
  workflow_dispatch:

  release:
    types: [published]



jobs:
  pypi-publish:
    name: Publish To PyPI

    runs-on: ubuntu-latest

    environment:
      name: ${{ 'pypi' }}
      url: https://pypi.org/p/${{ 'relic-tool-sga-v2' }}


    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        persist-credentials: false

    - name: Setup Python ${{ '3.x' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ '3.x' }}

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Build
      run: |
        python -m pip install build

    - name: Build Repo
      run: python -m build ${{ './src' }}

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
