name: Upload to Test PyPI

on:
  workflow_dispatch:

jobs:
  test-pypi-publish:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/publish-to-pypi.yml@main
    with:
      package-name: relic-tool-sga-v2
