name: Pytest

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
    - src/relic/**
    - tests/**
    - .github/workflows/pytest.yml
    - setup.cfg
    - setup.py
    - MANIFEST.in
    - test-requirements.txt

  pull_request:
    branches: [main]
    paths:
    - src/relic/**
    - tests/**
    - .github/workflows/pytest.yml
    - setup.cfg
    - setup.py
    - MANIFEST.in
    - test-requirements.txt

jobs:
  pytest:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/pytest.yml@main
